#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cc-oci-runtime
Version  : f124ab247fc2511522b0f8af7bae4667428d81a9
Release  : 5
URL      : https://github.com/01org/cc-oci-runtime/archive/f124ab247fc2511522b0f8af7bae4667428d81a9.tar.gz
Source0  : https://github.com/01org/cc-oci-runtime/archive/f124ab247fc2511522b0f8af7bae4667428d81a9.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: cc-oci-runtime-bin
Requires: cc-oci-runtime-data
BuildRequires : bats
BuildRequires : clear-containers-image
BuildRequires : cppcheck
BuildRequires : lcov
BuildRequires : linux-container
BuildRequires : pkgconfig(check)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(uuid)
BuildRequires : qemu-lite
BuildRequires : valgrind

%description
.. image:: https://travis-ci.org/01org/cc-oci-runtime.svg?branch=master
:target: https://travis-ci.org/01org/cc-oci-runtime

%package bin
Summary: bin components for the cc-oci-runtime package.
Group: Binaries
Requires: cc-oci-runtime-data

%description bin
bin components for the cc-oci-runtime package.


%package data
Summary: data components for the cc-oci-runtime package.
Group: Data

%description data
data components for the cc-oci-runtime package.


%prep
%setup -q -n cc-oci-runtime-f124ab247fc2511522b0f8af7bae4667428d81a9

%build
export LANG=C
%autogen --disable-static --enable-valgrind \
--enable-code-coverage \
--enable-cppcheck \
--disable-valgrind-memcheck \
--with-cc-kernel=/usr/share/clear-containers/vmlinux.container \
--with-cc-image=/usr/share/clear-containers/clear-containers.img
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cc-oci-runtime
/usr/bin/cc-oci-runtime.sh

%files data
%defattr(-,root,root,-)
/usr/share/defaults/cc-oci-runtime/cc-oci-runtime.sh.in
/usr/share/defaults/cc-oci-runtime/hypervisor.args
/usr/share/defaults/cc-oci-runtime/kernel-cmdline
/usr/share/defaults/cc-oci-runtime/vm.json
