#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cc-oci-runtime
Version  : 8c8b25e15101a04ed758ba486fc8be8076e40d7f
Release  : 12
URL      : https://github.com/01org/cc-oci-runtime/archive/8c8b25e15101a04ed758ba486fc8be8076e40d7f.tar.gz
Source0  : https://github.com/01org/cc-oci-runtime/archive/8c8b25e15101a04ed758ba486fc8be8076e40d7f.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0
Requires: cc-oci-runtime-bin
Requires: cc-oci-runtime-config
Requires: cc-oci-runtime-data
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : bats
BuildRequires : clear-containers-image
BuildRequires : cppcheck
BuildRequires : gettext-bin
BuildRequires : go
BuildRequires : lcov
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : linux-container
BuildRequires : m4
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(check)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(libmnl)
BuildRequires : pkgconfig(systemd)
BuildRequires : pkgconfig(uuid)
BuildRequires : qemu-lite
BuildRequires : systemd-dev
BuildRequires : valgrind
Patch1: 0001-build-add-autogopath.patch

%description
.. image:: https://travis-ci.org/01org/cc-oci-runtime.svg?branch=master
:target: https://travis-ci.org/01org/cc-oci-runtime

%package bin
Summary: bin components for the cc-oci-runtime package.
Group: Binaries
Requires: cc-oci-runtime-data
Requires: cc-oci-runtime-config

%description bin
bin components for the cc-oci-runtime package.


%package config
Summary: config components for the cc-oci-runtime package.
Group: Default

%description config
config components for the cc-oci-runtime package.


%package data
Summary: data components for the cc-oci-runtime package.
Group: Data

%description data
data components for the cc-oci-runtime package.


%package extras
Summary: extras components for the cc-oci-runtime package.
Group: Default

%description extras
extras components for the cc-oci-runtime package.


%prep
%setup -q -n cc-oci-runtime-8c8b25e15101a04ed758ba486fc8be8076e40d7f
%patch1 -p1

%build
export LANG=C
%autogen --disable-static --enable-valgrind \
--enable-code-coverage \
--enable-cppcheck \
--disable-valgrind-memcheck \
--with-cc-kernel=/usr/share/clear-containers/vmlinux.container \
--with-cc-image=/usr/share/clear-containers/clear-containers.img \
--with-cc-image-systemdsystemunitdir=/usr/lib/systemd/system
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cc-oci-runtime
/usr/bin/cc-oci-runtime.sh
/usr/libexec/cc-proxy
/usr/libexec/cc-shim

%files config
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/cc-agent.service
%exclude /usr/lib/systemd/system/cc-agent.target
%exclude /usr/lib/systemd/system/container-workload.service
%exclude /usr/lib/systemd/system/container.target
%exclude /usr/lib/systemd/system/opt-rootfs-proc.mount
%exclude /usr/lib/systemd/system/opt-rootfs-sys.mount
%exclude /usr/lib/systemd/system/opt-rootfs.mount
/usr/lib/systemd/system/cc-proxy.service
/usr/lib/systemd/system/cc-proxy.socket

%files data
%defattr(-,root,root,-)
/usr/share/defaults/cc-oci-runtime/hypervisor.args
/usr/share/defaults/cc-oci-runtime/kernel-cmdline
/usr/share/defaults/cc-oci-runtime/vm.json

%files extras
%defattr(-,root,root,-)
/usr/lib/systemd/system/cc-agent.service
/usr/lib/systemd/system/cc-agent.target
/usr/lib/systemd/system/container-workload.service
/usr/lib/systemd/system/container.target
/usr/lib/systemd/system/opt-rootfs-proc.mount
/usr/lib/systemd/system/opt-rootfs-sys.mount
/usr/lib/systemd/system/opt-rootfs.mount
